name: k6 stress (performance) test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Obtain Vercel preview deploy URL and run k6 test
    steps:
      - name: Wait for Vercel deploy
        run: sleep 30
      - name: Obtain Vercel preview deploy URL
        uses: zentered/vercel-preview-url@v1.0.0
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run k6 test
        uses: k6io/action@v0.2.0
        with:
          filename: k6/empty.js
        env:
          VERCEL_URL: ${{ steps.vercel_preview_url.outputs.preview_url }}
