# https://www.apollographql.com/docs/studio/github-integration/#github-actions

on:
  pull_request:
    branches: [main]

jobs:
  schema-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install --global @apollo/rover
      - name: Run schema check
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
          APOLLO_GRAPH_ID: ${{ secrets.APOLLO_GRAPH_ID }}
        run: |
          rover graph check ${{ env.APOLLO_GRAPH_ID }}@$current --schema ./src/schema/index.graphql
