name: Unit tests via Jest

on:
  pull_request:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SUPERUSER_TOKEN: ${{ secrets.SUPERUSER_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm install
      - run: npx jest --ci --testResultsProcessor=jest-junit

      - name: Make test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest Tests
          path: junit.xml
          reporter: jest-junit