name: Unit tests via Jest

on:
  pull_request:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SUPERUSER_TOKEN: ${{ secrets.SUPERUSER_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
      - run: npm install

      - name: Run Jest test with junit reporter
      - run: npx jest --ci --testResultsProcessor=jest-junit

      - name: Make test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest Tests
          path: junit.xml
          reporter: jest-junit